"""Turn the built single-file page into an editable multi-file workspace.

The pipeline always builds one self-contained `index.html` - the preview iframe, share link,
deploy step and browser checks all depend on that. These helpers derive sibling assets from it
so the workspace can offer `styles.css` / `app.js` / `README.md` without changing what the
agents emit or how the page is rendered.
"""
import re
from dataclasses import dataclass

STYLE_RE = re.compile(r"(<style[^>]*>)(.*?)(</style>)", re.S | re.I)
# Scripts that carry a src= or a non-JS type (JSON-LD etc.) stay inline; only real inline JS moves.
SCRIPT_RE = re.compile(r"(<script\b([^>]*)>)(.*?)(</script>)", re.S | re.I)
JS_TYPES = {"", "text/javascript", "application/javascript", "module", "text/ecmascript"}
ATTR_TYPE_RE = re.compile(r"""\btype\s*=\s*("([^"]*)"|'([^']*)'|([^\s>]+))""", re.I)


@dataclass(frozen=True)
class Asset:
    name: str
    language: str
    text: str
    note: str


def _script_type(attrs: str) -> str:
    m = ATTR_TYPE_RE.search(attrs or "")
    if not m:
        return ""
    return (m.group(2) or m.group(3) or m.group(4) or "").strip().lower()


def _moved_scripts(attrs: str) -> bool:
    """A script only moves to app.js when it has no src and a JavaScript type."""
    return "src=" not in (attrs or "").lower() and _script_type(attrs) in JS_TYPES


def split_page(html: str) -> tuple[str, list[Asset]]:
    """Split a page into (standalone_html, assets).

    `standalone_html` is the same document with the moved blocks replaced by references, so it
    renders next to the extracted files. Assets are returned in workspace order; empty ones are
    skipped so a page with no JavaScript does not ship an empty app.js.
    """
    sheets = [body.strip("\n") for _, body, _ in STYLE_RE.findall(html) if body.strip()]
    styles = "\n\n".join(sheets).rstrip() + ("\n" if sheets else "")

    scripts = [body.strip("\n") for open_tag, attrs, body, _ in SCRIPT_RE.findall(html)
               if _moved_scripts(attrs) and body.strip()]
    app_js = "\n\n".join(scripts).rstrip() + ("\n" if scripts else "")

    def drop_script(match):
        if not _moved_scripts(match.group(2)):
            return match.group(0)
        return '<script src="app.js"></script>' if app_js else ""

    standalone = SCRIPT_RE.sub(drop_script, html)
    if styles:
        state = {"first": True}

        def drop_style(match):
            if state["first"]:
                state["first"] = False
                return '<link rel="stylesheet" href="styles.css">'
            return ""  # extra style blocks fold into the single stylesheet

        standalone = STYLE_RE.sub(drop_style, standalone)

    assets: list[Asset] = []
    if styles:
        assets.append(Asset("styles.css", "css", styles, f"{len(sheets)} style block(s) from the page"))
    if app_js:
        assets.append(Asset("app.js", "js", app_js, f"{len(scripts)} inline script(s) from the page"))
    return standalone, assets


def readme(idea: str, files: list[Asset], version: int, readiness: int | None) -> Asset:
    """A short handoff note so the folder explains itself once downloaded."""
    lines = [f"# {idea.strip() or 'Landing page'}", "",
             f"Generated by Launch Crew - page version v{version}"
             + (f", launch readiness {readiness}/100." if readiness is not None else "."),
             "", "## Files", ""]
    for f in files:
        lines.append(f"- **{f.name}** - {f.note}")
    lines += ["", "## Preview", "",
              "`index.html` is self-contained: open it in any browser as-is.",
              "The extracted assets are for editing. After changing `styles.css` or `app.js`, open",
              "the sibling `index.html` (it links to them) to see your edits.", "",
              "## Notes", "",
              "- No build step, no dependencies: plain HTML, CSS and JavaScript.",
              "- The deployed page always uses the self-contained version."]
    return Asset("README.md", "md", "\n".join(lines) + "\n", "Handoff notes")
